# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63d124fdf006076fdd4b742ca71feba3"
name = "Floating Cart Button"
application_url = "http://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "flotingapp.myshopify.com"

[webhooks]
api_version = "2025-01"

  

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_script_tags,read_metafields,write_metafields"

[auth]
redirect_urls = [
  "http://localhost:3000/api/auth/callback"
]

[[extensions]]
type = "theme"
name = "floating-cart-extension"
handle = "floating-cart-extension"
